### ISSUE TITLE
CRITICAL: 403 Forbidden when attempting to modify panel content

### ISSUE THREAD

**Issue by srees** [d6lts/panels#2]
This makes panels unusable.

Go to an existing panel listing, edit content for one of them, and attempt to add content to a pane.

I'm trying to figure out how to backport http://cgit.drupalcode.org/panels/commit/?id=a8b2e2be73484e66fd6e020e0038a6a0aa8f2296 however there doesn't appear to be an alter on the handlers in D6. Sigh.

**Comment by dsnopek** [comment]
That commit is altering Panels displays exported to code so that they don't have to be re-exported. Re-saving, and then re-exporting your Panels displays to code should have the same effect!

**Comment by srees** [comment]
Ok, perhaps I found the wrong patch to explore.
The logs show this when attempting to add content to a panel:

```
Type:   access denied
Location:   https://localhost/panels/ajax/editor/select-content/688/top
Referrer:   https://localhost/node/3767/og_panels/688/panel_content?destination=node%2F3767%2Fog_panels
Message:    panels/ajax/editor/select-content/688/top
```

We haven't upgraded our site yet due to its size and complexity. Going through hundreds of panels displays to re-save isn't a practical solution.

Logically, I looked through the new code, found 'function access' in the panels_display class, and traced which section was returning FALSE. It is the line (panels.module)
`if (empty($this->storage_type) || empty($this->storage_id)) {`

Both values are empty for our panels. So the patch I referenced looked logical, and was one of a couple that referenced the specific issue of access denied popping up in the D7 version. It is simply setting a value if one doesn't exist.

However, I can't find where I would go to do this in D6. The alter hook isn't implemented as far as I can tell, and I can't just embed the code in the access function because I don't have the same variables available.

Clearly I'm putting effort into googling and solving this myself, I just lack the understanding of the panels module and how to backport D7 stuff.
If I'm barking up the wrong tree, please at least link slap me with somewhere I can find the solution, or I will have to roll back this severely flawed 'security' release from our production server today.

**Comment by dsnopek** [comment]
Just to double check: are your Panels displays in code or in the database? The commit you referenced was for Panels displays in code, but it isn't clear from your response if that's the case or not. If they're in code, then theoretically running update.php or `drush updb` should update your Panels displays to have the right storage_type and storage_id.

However, I noticed the 'og_panels' in the URL you gave above, and (depending on how og_panels works - I've never used it) it's possible that it needs to be patched to work with the new Panels storage API that was added to fix the security issue. So, _that_ could be the issue...

**Comment by srees** [comment]
It's probably a mix, but mostly database. I'll start looking at the og aspect as a possibility.

**Comment by srees** [comment]
Ok, probably not just OG.
I can go to edit a global layout at admin/build/panels/layouts/list/modboard/edit
and I still get the error with any region/row/column/etc settings.
An error occurred at /panels/ajax/editor/layout/builder-modboard/settings/blocks.
Error Description: 403: Forbidden

**Comment by dsnopek** [comment]
Sorry for the delay!

I've attempted to backport the recent Panels 7.x-3.x changes to 6.x-3.x. I haven't had a chance to do much testing yet, but I thought I'd let you know right away.

Here's the PR:

https://github.com/d6lts/panels/pull/3

(Once that's tested to work, I'll probably squash it down into one commit to clean up the history...)

If you have a chance to test it, please let me know if it helps in your use case!

> however there doesn't appear to be an alter on the handlers in D6

So, looking at ctools/includes/export.inc and ctools/page_manager/page_manager.install it really seems like the same alter should exist on default handlers, but I haven't had a chance to actually test it yet.

**Comment by dsnopek** [comment]
Ok, I finally got around to really testing the code in PR #3! I put some more details there, but long story short: it fixed all the problems I expected it to fix, including page_manager pages defined in code (the alter hook does work).

Committed in b02ffbb

@srees Please let me know if you have a chance to try it! It'd be great to confirm that it fixed at least some of your problems. I'll make a new release either shortly after you confirm, or in a couple days, regardless

**Comment by srees** [comment]
Sorry, I had pulled this from our dev environment as it was causing so much havoc for our team. I'll try to have a look today.

**Comment by dsnopek** [comment]
Ok, thanks! Sorry for taking so long to get to this - none of our customers were affected by the regressions, so it got prioritized lower :-/

**Comment by srees** [comment]
The same issues persist.
However, I'm testing a little more thoroughly. Managing an actual page _works_, but managing a custom layout _does not_ (there's no page manager handler), and og does not work either, of course.
Perhaps for your customers, they weren't messing with custom layouts or OG. Digging a little deeper, it seems to be that the db update to the panels_display doesn't assign a default type or id in these cases, and it isn't assumed in the code if it's missing. It just results in access denied.

I don't expect you to just 'fix' the og for us without pay, but I'm hoping the layout will at least fall under the module work you are already committed to.

**Comment by dsnopek** [comment]
> Managing an actual page works, but managing a custom layout does not (there's no page manager handler)

Ah, you mean configuring a "Flexible" layout? There's an unfixed issue for that in D7 too:

https://www.drupal.org/node/2790075

There isn't a solution for this yet. We'll probably need to fix it in D7 first and then backport it.

> Digging a little deeper, it seems to be that the db update to the panels_display doesn't assign a default type or id in these cases, and it isn't assumed in the code if it's missing.

Right, modules that create and use Panels displays now need to provide a "panels_storage" plugin to tell Panels how access works for their Panels displays, otherwise Panels is unable to check if the user has access to edit or render them. (FYI, without the fix even anonymous users are able to render any pane on any display or access it's configuration forms if they know the ids.)

So, panels_node, panels_mini, page_manager and panelizer (at least in D7) needed to have "panels_storage" plugins created, and that's why the update hooks specifically address Panels displays provided by each module. There can't really be a default because each of those modules (and any others like og_panels) all do their access control differently. And we have to default to disallowing access if there is no storage type/id set because otherwise we're just leaving the security hole open by default.

I hope that makes sense!

**Comment by srees** [comment]
I've got it working now, between your patches and a patch I've written for og_panels. Other than flexible layouts, of course.

**Comment by dsnopek** [comment]
> I've got it working now, between your patches and a patch I've written for og_panels

Ah, than's great! Did you post your og_panels patch to the queue? I'd be very curious to see it.

> Other than flexible layouts, of course.

I just attempted to reproduce the issue with Flexible layouts (on both D7 and D6), and found that it (at least for me) it's fixed by an existing D7 patch, which I actually already integrated into the D6 changes (because it's RTBC).

So, with my latest commit to the D6LTS panels, the Flexible layout stuff is all actually working for me. :-/

Can you give steps to reproduce it with the latest code from this repo? Thanks!

**Comment by srees** [comment]
I'm happy to post the og_panels patch, it's simply creating the plugin and integrating changes as indicated in the D6UPDATE.txt file. Where do you want it? I'm really not sure since the end of D6 support...

Am I supposed to use 6.x-3.x branch, or d6-latest-storage-fixes for testing the backports? On the 9th I pulled down the 6.x-3.x. I just tried the latest-storage-fixes, and it still fails.

Reproduction should be simple - go to admin/build/panels/layouts and click 'Add flexible layout'. In the section at the bottom (ie., 'Canvas'), select any of the drop-down arrows and choose settings. 403 forbidden.

**Comment by srees** [comment]
[og_panels_storage.patch.txt](https://github.com/d6lts/panels/files/468152/og_panels_storage.patch.txt)

**Comment by dsnopek** [comment]
> Reproduction should be simple - go to admin/build/panels/layouts and click 'Add flexible layout'. In the section at the bottom (ie., 'Canvas'), select any of the drop-down arrows and choose settings. 403 forbidden.

Hrm. That is really, really weird because it's currently working for me. Maybe I need to wipe out my development environment and start over just in case there's something in there that's making my results different than yours...

**Comment by srees** [comment]
Logging in the access function indicates it's because it doesn't have storage_type/id set, I'm just not sure where to address that for the layouts. And, to be sure, I blew away my panels folder and used a fresh download. ;) Even reset the module version in the database and re-ran the updates.

**Comment by srees** [comment]
Don't sweat it for me, I consulted with our content managers and we don't actually use the stored flexible layouts right now, so it doesn't matter to us that it doesn't work.

**Comment by dsnopek** [comment]
@srees I just made a PR that backports a patch to fix the flexible layouts issue in D7 (I finally figured out why I was having trouble reproducing it - it was my mistake):

https://github.com/d6lts/panels/pull/4

Please let me know if that fixes this for you! Thanks :-)

**Comment by dsnopek** [comment]
I just merged #4 and made a new release https://github.com/d6lts/panels/releases/tag/6.x-3.14

I hope this fixes the last of your issues! I'm going to mark this as closed, but we can re-open if it didn't fix it. Thanks for your help on this!
